version: "3.9"

services:
  data-generator:
    build: .
    image: python_data_generator
    container_name: mySQL_Example
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    ports:
      - "${PORT}:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mySQL-Example-Data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PORT: ${PORT}

volumes:
  mySQL-Example-Data:
